/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export interface CategoryTotal { 'total' : bigint, 'category' : Category }
export interface Expense {
  'id' : string,
  'date' : string,
  'note' : [] | [string],
  'createdAt' : Time,
  'updatedAt' : Time,
  'category' : Category,
  'amount' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addExpense' : ActorMethod<
    [string, bigint, Category, string, [] | [string]],
    Expense
  >,
  'deleteExpense' : ActorMethod<[string], undefined>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getCategoryTotals' : ActorMethod<[], Array<CategoryTotal>>,
  'getExpense' : ActorMethod<[string], Expense>,
  'getExpensesByCategory' : ActorMethod<[Category], Array<Expense>>,
  'getExpensesByDate' : ActorMethod<[string], Array<Expense>>,
  'getExpensesByDateRange' : ActorMethod<[string, string], Array<Expense>>,
  'getTotalByCategory' : ActorMethod<[Category], bigint>,
  'getTotalExpenses' : ActorMethod<[], bigint>,
  'updateExpense' : ActorMethod<
    [string, bigint, Category, string, [] | [string]],
    Expense
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];