/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Text;
export const Time = IDL.Int;
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'updatedAt' : Time,
  'category' : Category,
  'amount' : IDL.Nat,
});
export const CategoryTotal = IDL.Record({
  'total' : IDL.Nat,
  'category' : Category,
});
export const Currency = IDL.Variant({
  'INR' : IDL.Null,
  'JPY' : IDL.Null,
  'USD' : IDL.Null,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Nat, Category, IDL.Text, IDL.Opt(IDL.Text)],
      [Expense],
      [],
    ),
  'deleteExpense' : IDL.Func([IDL.Text], [], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getCategoryTotals' : IDL.Func([], [IDL.Vec(CategoryTotal)], ['query']),
  'getCurrencyPreference' : IDL.Func([], [Currency], ['query']),
  'getExpense' : IDL.Func([IDL.Text], [Expense], ['query']),
  'getExpensesByCategory' : IDL.Func([Category], [IDL.Vec(Expense)], ['query']),
  'getExpensesByDate' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getExpensesByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getTotalByCategory' : IDL.Func([Category], [IDL.Nat], ['query']),
  'getTotalExpenses' : IDL.Func([], [IDL.Nat], ['query']),
  'setCurrencyPreference' : IDL.Func([Currency], [], []),
  'updateExpense' : IDL.Func(
      [IDL.Text, IDL.Nat, Category, IDL.Text, IDL.Opt(IDL.Text)],
      [Expense],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Text;
  const Time = IDL.Int;
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'updatedAt' : Time,
    'category' : Category,
    'amount' : IDL.Nat,
  });
  const CategoryTotal = IDL.Record({
    'total' : IDL.Nat,
    'category' : Category,
  });
  const Currency = IDL.Variant({
    'INR' : IDL.Null,
    'JPY' : IDL.Null,
    'USD' : IDL.Null,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Nat, Category, IDL.Text, IDL.Opt(IDL.Text)],
        [Expense],
        [],
      ),
    'deleteExpense' : IDL.Func([IDL.Text], [], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getCategoryTotals' : IDL.Func([], [IDL.Vec(CategoryTotal)], ['query']),
    'getCurrencyPreference' : IDL.Func([], [Currency], ['query']),
    'getExpense' : IDL.Func([IDL.Text], [Expense], ['query']),
    'getExpensesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByDate' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
    'getExpensesByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getTotalByCategory' : IDL.Func([Category], [IDL.Nat], ['query']),
    'getTotalExpenses' : IDL.Func([], [IDL.Nat], ['query']),
    'setCurrencyPreference' : IDL.Func([Currency], [], []),
    'updateExpense' : IDL.Func(
        [IDL.Text, IDL.Nat, Category, IDL.Text, IDL.Opt(IDL.Text)],
        [Expense],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };